#base "../customizations/Streaming/hudlayout.res"
#base "hudlayout_natalie.res"
#base "hudlayout_default.res"
#base "../customizations/Crosshair.res"
#base "../customizations/HitMarkers.res"
#base "../customizations/TransparentViewmodels.res"